#!/bin/bash
set -xe

#-------------------------------------------------------------------------------
# dependencies
#-------------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends python-software-properties software-properties-common
add-apt-repository ppa:sebdoido/spotify-dh-virtualenv-stable-${application_version}

apt-get update
apt-get install -y --no-install-recommends \
  build-essential \
  curl \
	debhelper \
	devscripts \
  dh-virtualenv=${application_version}\* \
	equivs \
	git-core \
  libjs-sphinxdoc \
  libwww-perl \
	python-dev \
	python-all \
	python-pip \
	python-setuptools \
  python-virtualenv

curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python2.7
pip --version

#-------------------------------------------------------------------------------
# scripts
#-------------------------------------------------------------------------------
cp -R /tmp/resources/usr /

#-------------------------------------------------------------------------------
# cleanup
#-------------------------------------------------------------------------------
apt-get clean
