#!/bin/bash
set -xe

#-------------------------------------------------------------------------------
# dependencies
#-------------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends software-properties-common

apt-get update
apt-get install -y --no-install-recommends \
  build-essential \
  curl \
	debhelper \
	devscripts \
  dh-virtualenv \
	equivs \
	git-core \
  libjs-sphinxdoc \
  libwww-perl \
	python-dev \
	python-all \
	python-pip \
	python-setuptools \
  python-virtualenv \
  python3-dev \
  python3-pip \
  python3-venv

pip --version

#-------------------------------------------------------------------------------
# scripts
#-------------------------------------------------------------------------------
cp -R /tmp/resources/usr /

#-------------------------------------------------------------------------------
# cleanup
#-------------------------------------------------------------------------------
apt-get clean
